version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-chatbot
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_PERSONALIZATION_ENABLED=true
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
